services:
  app:
    build: ./
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./:/usr/src/app/
    ports:
      - '8000:8000'
    env_file:
      - ./.env.docker
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/pgdata
    environment:
      - POSTGRES_DB=storing_links
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
volumes:
  postgres_data: